version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins-lts
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  config-server:
    image: turkuazsengul/config-server:latest
    ports:
      - '8888:8888'
  front:
    image: turkuazsengul/front:latest
    ports:
      - '3000:3000'
  login:
    image: turkuazsengul/login:latest
    depends_on:
      - config-server
      - mongodb
    ports:
      - '8091:8091'
    environment:
      - SPRING_PROFILES_ACTIVE=images
  images:
    image: turkuazsengul/images:latest
    depends_on:
      - config-server
      - mongodb
    ports:
      - '8092:8092'
volumes:
  dbdata6: